package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Slider;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ajustes_ventana extends VerticalLayout {
	protected VerticalLayout ajustesMain;
	protected Button back;
	protected Button modificar_perfil;
	protected Button eliminar_cuenta;
	protected Slider notificar_me_gusta;
	protected Slider notificar_comentarios;
	protected Slider notificar_seguimiento;
	protected Slider notificar_solicitud;
	protected Slider perfil_publico;
	protected Slider mostrar_seguidores;
	protected Button usuarios_bloqueados;
	protected Button cerrar_sesion;

	public Ajustes_ventana() {
		Design.read(this);
	}
}
