package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Iniciar_sesion_ventana extends AbsoluteLayout {
	protected AbsoluteLayout mainLayout;
	protected Image imagenPrincipal;
	protected VerticalLayout loginVertLayout;
	protected TextField textFieldUsuario;
	protected PasswordField textFieldContraseña;
	protected HorizontalLayout horizontalBotones;
	protected NativeButton buttonIniciarSesionInv;

	public Iniciar_sesion_ventana() {
		Design.read(this);
	}
}
