package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Listado_de_publicaciones_inv_ventana extends VerticalLayout {
	protected Image fotoPerfil2;
	protected Image fotoPerfil21;
	protected Image fotoPerfil22;
	protected Image fotoPerfil23;
	protected Image fotoPerfil24;
	protected Image fotoPerfil25;
	protected Image fotoPerfil26;
	protected Image fotoPerfil27;

	public Listado_de_publicaciones_inv_ventana() {
		Design.read(this);
	}
}
