package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Subir_publicacion_ventana extends VerticalLayout {
	protected HorizontalLayout usuarioPublicacion;
	protected Image fotoPerfil;
	protected Button botonAñadir;
	protected Button botonPublicar;
	protected VerticalLayout tabSheetContainer;
	protected TabSheet tabSheet;
	protected Image imagen;
	protected TextArea descripcionAreaSubir;

	public Subir_publicacion_ventana() {
		Design.read(this);
	}
}
