package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_publicacion_admin_ventana extends VerticalLayout {
	protected HorizontalLayout usuarioPublicacion;
	protected Image fotoPerfil;
	protected TabSheet tabSheet;
	protected Image imagen;
	protected HorizontalLayout lyAcciones;
	protected Button me_gusta;
	protected Button comentar;
	protected Button eliminarEtiqueta;
	protected Button eliminarPublicacion;
	protected Button compartir;
	protected VerticalLayout comentarios;
	protected HorizontalLayout comentarioVista;
	protected Button eliminarComentarioButton;
	protected HorizontalLayout comentarioVista1;
	protected Button eliminarComentarioButton1;
	protected HorizontalLayout comentarioVista2;
	protected Button eliminarComentarioButton2;

	public Ver_publicacion_admin_ventana() {
		Design.read(this);
	}
}
