package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_usuario_propio_ventana extends VerticalLayout {
	protected Button back;
	protected HorizontalLayout barra_perfil_usuario;
	protected Image imagen_perfil_ajeno;
	protected Label nombre_usuario;
	protected GridLayout grid_informacionUsuario;
	protected VerticalLayout publicacionesPerfil;
	protected VerticalLayout publicacionesEtiquetadas;
	protected VerticalLayout publicacionesActividad;
	protected VerticalLayout actividadContent;
	protected HorizontalLayout actividad;
	protected VerticalLayout actividadContent1;
	protected HorizontalLayout actividad1;
	protected VerticalLayout actividadContent2;
	protected HorizontalLayout actividad2;
	protected VerticalLayout actividadContent3;
	protected HorizontalLayout actividad3;
	protected VerticalLayout actividadContent4;
	protected HorizontalLayout actividad4;
	protected VerticalLayout actividadContent5;
	protected HorizontalLayout actividad5;

	public Ver_usuario_propio_ventana() {
		Design.read(this);
	}
}
