package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_usuario_inv_ventana extends VerticalLayout {
	protected Button back;
	protected HorizontalLayout barra_perfil_usuario;
	protected Image imagen_perfil_ajeno;
	protected Label nombre_usuario;
	protected GridLayout grid_informacionUsuario;
	protected VerticalLayout publicaciones;

	public Ver_usuario_inv_ventana() {
		Design.read(this);
	}
}
