package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_listado_de_publicaciones_ventana extends VerticalLayout {
	protected Button back;
	protected HorizontalLayout usuarioPublicacion;
	protected Image fotoPerfil;
	protected TabSheet tabSheet;
	protected Image imagen;
	protected HorizontalLayout opcionesImagen;
	protected Button me_gusta;
	protected Button comentar;
	protected Button eliminarEtiqueta;
	protected Button eliminarPublicacion;
	protected Button compartir;
	protected HorizontalLayout usuarioPublicacion1;
	protected Image fotoPerfil1;
	protected TabSheet tabSheet1;
	protected Image imagen1;
	protected HorizontalLayout opcionesImagen1;
	protected Button me_gusta1;
	protected Button comentar1;
	protected Button eliminarEtiqueta1;
	protected Button eliminarPublicacion1;
	protected Button compartir1;
	protected HorizontalLayout usuarioPublicacion2;
	protected Image fotoPerfil2;
	protected TabSheet tabSheet2;
	protected Image imagen2;
	protected HorizontalLayout opcionesImagen2;
	protected Button me_gusta2;
	protected Button comentar2;
	protected Button eliminarEtiqueta2;
	protected Button eliminarPublicacion2;
	protected Button compartir2;

	public Ver_listado_de_publicaciones_ventana() {
		Design.read(this);
	}
}
