package com.instagual.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_notificaciones_ventana extends VerticalLayout {
	protected Button back;
	protected VerticalLayout actividadContent;
	protected HorizontalLayout actividad;
	protected VerticalLayout actividadContent1;
	protected HorizontalLayout actividad1;
	protected VerticalLayout actividadContent2;
	protected HorizontalLayout actividad2;
	protected VerticalLayout actividadContent3;
	protected HorizontalLayout actividad3;
	protected VerticalLayout actividadContent4;
	protected HorizontalLayout actividad4;
	protected VerticalLayout actividadContent5;
	protected HorizontalLayout actividad5;
	protected VerticalLayout notificacionesContent;
	protected HorizontalLayout notificacion;

	public Ver_notificaciones_ventana() {
		Design.read(this);
	}
}
