package user_interface;

public class Ver_usuario__admin_ extends Ver_usuario_busqueda_inv_ {
	public Ver_publicacion__admin_ _ver_publicacion__admin_;
	public Usuario_busqueda__admin_ _usuario_busqueda__admin_;
	public Ver_listado_de_etiquetas_usuario__admin_ _ver_listado_de_etiquetas_usuario__admin_;
	public Ver_listado_de_publicaciones_usuario__admin_ _ver_listado_de_publicaciones_usuario__admin_;
	public Ver_publicacion_actividad _ver_publicacion_actividad;
	public Ver_usuario_actividad _ver_usuario_actividad;
}